package _2;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * <p>
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * <p>
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class Solution {
    public static void main(String[] args) {
        int val_prev = 1;
        int val = 2;
        int sum = 0;
        while (val < 4000000) {
            if (val%2 == 0) {
                sum = sum + val;
                System.out.println(val);
//                System.out.println(sum);
            }
            int tmp = val + val_prev;
            val_prev = val;
            val = tmp;


        }
        System.out.println(sum);
    }
}
